<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>AzuModsValheim1Compat</AssemblyName>
    <RootNamespace>AzuModsValheim1Compat</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <Version>1.0.6</Version>
    <Authors>Aborigen</Authors>
    <Description>BepInEx Preloader compatibility patch for Azumatt mods on Valheim 1.0.7</Description>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>lib\BepInEx.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Mono.Cecil">
      <HintPath>lib\Mono.Cecil.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

</Project>